/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "include/ffmpeg.h"
#include <android/log.h>
/* Header for class com_lyman_ffmpeg_cmake_single_utils_FFmpegKit */

#ifndef _Included_com_lyman_ffmpeg_cmake_single_utils_FFmpegKit
#define _Included_com_lyman_ffmpeg_cmake_single_utils_FFmpegKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lyman_ffmpeg_cmake_single_utils_FFmpegKit
 * Method:    run
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_lyman_ffmpeg_1cmake_1single_utils_FFmpegKit_run
        (JNIEnv *env, jclass obj, jobjectArray commands) {
    int argc = (*env)->GetArrayLength(env, commands);
    char *argv[argc];

    __android_log_print(ANDROID_LOG_ERROR, "Kit", "argc %d\n", argc);
    int i;
    for (i = 0; i < argc; i++) {
        jstring js = (jstring) (*env)->GetObjectArrayElement(env, commands, i);
        argv[i] = (char *) (*env)->GetStringUTFChars(env, js, 0);
        __android_log_print(ANDROID_LOG_ERROR, "Kit", "argv %s\n", argv[i]);
    }
    return run(argc, argv);
}

#ifdef __cplusplus
}
#endif
#endif
